import { useState, useEffect, useRef } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { cn } from "@/lib/utils";

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";

import {
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
} from "@/components/ui/tabs";

import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";

import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { Switch } from "@/components/ui/switch";
import { Separator } from "@/components/ui/separator";
import { Slider } from "@/components/ui/slider";
import { ScrollArea } from "@/components/ui/scroll-area";

import {
  ArrowRight,
  Download,
  Edit,
  Eye,
  FileText,
  GridIcon,
  ImageIcon,
  Layers,
  Layout,
  List,
  ListFilter,
  Loader2,
  PanelLeft,
  PanelRight,
  PanelTop,
  RefreshCw,
  Settings,
  Sparkles,
  Check,
  X,
} from "lucide-react";

// Define the report templates
const reportTemplates = [
  // Standard Snagging templates
  {
    id: "default",
    name: "Standard Report",
    description: "Comprehensive inspection report with detailed defect analysis",
    preview: "/images/report-templates/standard.png", // This would be a screenshot of the report
    type: "snagging"
  },
  {
    id: "executive",
    name: "Executive Summary",
    description: "Focused report with key findings and recommendations",
    preview: "/images/report-templates/executive.png",
    type: "snagging"
  },
  {
    id: "detailed",
    name: "Detailed Technical",
    description: "In-depth technical report with comprehensive appendices",
    preview: "/images/report-templates/detailed.png",
    type: "snagging"
  },
  
  // RERA Audit templates
  {
    id: "condition_survey",
    name: "Condition Survey",
    description: "Comprehensive building condition assessment using RICS NRM3 classification",
    preview: "/images/report-templates/condition_survey.png",
    type: "rera_audit"
  },
  {
    id: "reserve_fund",
    name: "Reserve Fund Analysis",
    description: "In-depth analysis of building components with lifecycle costs and replacement schedules",
    preview: "/images/report-templates/reserve_fund.png",
    type: "rera_audit"
  }
];

// Define report customization options
interface ReportSettings {
  template: string;
  projectType?: string; // 'snagging' or 'rera_audit'
  companyLogo: boolean;
  coverPage: boolean;
  executiveSummary: string;
  includeImages: boolean;
  includeAnnotations: boolean;
  groupByLocation: boolean;
  groupBySeverity: boolean;
  groupByCategory: boolean;
  showDates: boolean;
  showAssignees: boolean;
  includeAppendix: boolean;
  conclusion: string;
  customHeader: string;
  customFooter: string;
  includeRecommendations: boolean;
  fontSizeScale: number;
  colorTheme: string;
  // RERA Audit specific settings
  includeLifecycleCosts?: boolean;
  includeReplacementSchedule?: boolean;
  includeConditionRatings?: boolean;
  includeNRM3Classification?: boolean;
}

// Default settings
const defaultSettings: ReportSettings = {
  template: "default",
  projectType: "snagging", // Default to snagging project type
  companyLogo: true,
  coverPage: true,
  executiveSummary: "",
  includeImages: true,
  includeAnnotations: true,
  groupByLocation: true,
  groupBySeverity: false,
  groupByCategory: false,
  showDates: true,
  showAssignees: true,
  includeAppendix: true,
  conclusion: "",
  customHeader: "",
  customFooter: "Report generated by Snagging.me by UrbanGrid",
  includeRecommendations: true,
  fontSizeScale: 1,
  colorTheme: "blue",
  // RERA Audit specific settings (defaults)
  includeLifecycleCosts: true,
  includeReplacementSchedule: true,
  includeConditionRatings: true,
  includeNRM3Classification: true
};

// Define the color themes
const colorThemes = [
  { id: "blue", name: "Blue (Default)", primary: "#2563eb", secondary: "#93c5fd" },
  { id: "green", name: "Green", primary: "#16a34a", secondary: "#86efac" },
  { id: "purple", name: "Purple", primary: "#9333ea", secondary: "#d8b4fe" },
  { id: "red", name: "Red", primary: "#dc2626", secondary: "#fecaca" },
  { id: "amber", name: "Amber", primary: "#d97706", secondary: "#fde68a" },
  { id: "teal", name: "Teal", primary: "#0d9488", secondary: "#99f6e4" },
];

interface ReportEditorProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  projectId: number;
  projectName: string;
}

export default function ReportEditor({
  open,
  onOpenChange,
  projectId,
  projectName
}: ReportEditorProps) {
  const [activeTab, setActiveTab] = useState("template");
  const [settings, setSettings] = useState<ReportSettings>(defaultSettings);
  const [previewLoading, setPreviewLoading] = useState(false);
  const [projectType, setProjectType] = useState<string>("snagging");
  const previewIframeRef = useRef<HTMLIFrameElement>(null);
  const { toast } = useToast();
  const queryClient = useQueryClient();
  
  // Fetch project details to get project type
  useEffect(() => {
    if (open && projectId) {
      const fetchProjectType = async () => {
        try {
          const response = await fetch(`/api/projects/${projectId}`);
          if (response.ok) {
            const project = await response.json();
            const type = project.projectType || "snagging";
            setProjectType(type);
            
            // Update settings with the project type
            setSettings(prev => ({
              ...prev,
              projectType: type,
              // If the template doesn't match the project type, set a default template for that type
              template: reportTemplates.find(t => t.type === type && t.id === prev.template) 
                ? prev.template 
                : reportTemplates.find(t => t.type === type)?.id || prev.template
            }));
          }
        } catch (error) {
          console.error("Error fetching project type:", error);
        }
      };
      
      fetchProjectType();
    }
  }, [open, projectId]);

  // Generate report mutation
  const generateReportMutation = useMutation({
    mutationFn: async (reportSettings: ReportSettings) => {
      return await apiRequest(`/api/projects/${projectId}/generate-report`, {
        method: "POST",
        body: JSON.stringify({ settings: reportSettings }),
      });
    },
    onSuccess: (data) => {
      toast({
        title: "Report generated",
        description: "Inspection report has been generated successfully",
      });

      // Download the PDF report
      const reportUrl = `/api/generate-project-pdf/${projectId}?template=${settings.template}`;
      window.open(reportUrl, "_blank");
      
      // Close the dialog
      onOpenChange(false);
    },
    onError: (error: any) => {
      toast({
        title: "Failed to generate report",
        description: error.message || "An unexpected error occurred",
        variant: "destructive",
      });
    },
  });

  // Load preview in iframe
  const loadPreview = async () => {
    if (!previewIframeRef.current || !open) return;
    
    console.log("Starting report preview loading...");
    console.log("Project ID:", projectId);
    console.log("Report settings:", settings);
    
    setPreviewLoading(true);
    
    try {
      console.log("Fetching preview from server...");
      const response = await fetch(`/api/preview-project-report/${projectId}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ settings })
      });
      
      if (!response.ok) {
        console.error("Preview response error:", response.status, response.statusText);
        throw new Error(`Server error: ${response.status} ${response.statusText}`);
      }
      
      console.log("Preview response received:", response.status, response.headers.get('Content-Type'));
      const html = await response.text();
      console.log("Preview HTML length:", html.length);
      
      // Update the iframe content
      const iframe = previewIframeRef.current;
      if (!iframe) {
        console.error("Preview iframe reference not available");
        return;
      }
      
      console.log("Updating iframe content...");
      const iframeDoc = iframe.contentDocument || iframe.contentWindow?.document;
      
      if (iframeDoc) {
        iframeDoc.open();
        iframeDoc.write(html);
        iframeDoc.close();
        console.log("Preview loaded successfully");
      } else {
        console.error("Could not access iframe document");
      }
    } catch (error: any) {
      console.error('Error loading preview:', error);
      toast({
        title: "Preview failed",
        description: `Failed to generate report preview: ${error.message || 'Unknown error'}`,
        variant: "destructive",
      });
    } finally {
      setPreviewLoading(false);
    }
  };

  // Refresh preview
  const handleRefreshPreview = () => {
    loadPreview();
  };
  
  // Legacy preview in new window
  const handlePreview = () => {
    setPreviewLoading(true);
    const previewUrl = `/api/preview-project-report/${projectId}?template=${settings.template}`;
    window.open(previewUrl, "_blank");
    setPreviewLoading(false);
  };

  // Handle form submission
  const handleSubmit = () => {
    generateReportMutation.mutate(settings);
  };
  
  // Load preview when the dialog opens or settings change
  useEffect(() => {
    if (open && activeTab === "preview") {
      loadPreview();
    }
  }, [open, activeTab, settings]);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-4xl h-[85vh] flex flex-col overflow-hidden">
        <DialogHeader>
          <DialogTitle className="text-xl font-bold">
            Customize Inspection Report
          </DialogTitle>
          <DialogDescription>
            Create a professional inspection report for {projectName}. Customize the layout, content, and style to meet your specific needs.
          </DialogDescription>
        </DialogHeader>

        <div className="flex-1 flex flex-col overflow-hidden">
          <Tabs
            value={activeTab}
            onValueChange={setActiveTab}
            className="flex-1 flex flex-col overflow-hidden"
          >
            <TabsList className="grid grid-cols-4">
              <TabsTrigger value="template" className="flex items-center gap-2">
                <Layout className="h-4 w-4" />
                Template
              </TabsTrigger>
              <TabsTrigger value="content" className="flex items-center gap-2">
                <FileText className="h-4 w-4" />
                Content
              </TabsTrigger>
              <TabsTrigger value="style" className="flex items-center gap-2">
                <Settings className="h-4 w-4" />
                Style & Branding
              </TabsTrigger>
              <TabsTrigger value="preview" className="flex items-center gap-2">
                <Eye className="h-4 w-4" />
                Preview
              </TabsTrigger>
            </TabsList>

            <ScrollArea className="flex-1 mt-4 overflow-y-auto">
              <TabsContent value="template" className="mt-0 p-4 h-[500px]">
                <div className="flex items-center justify-between mb-4">
                  <h3 className="text-lg font-medium">Select Report Template</h3>
                  <div className="text-sm text-muted-foreground">
                    Project Type: <span className="font-medium capitalize">{settings.projectType === 'rera_audit' ? 'RERA Audit' : 'Snagging'}</span>
                  </div>
                </div>
                
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  {reportTemplates
                    .filter(template => template.type === settings.projectType)
                    .map((template) => (
                    <Card 
                      key={template.id} 
                      className={cn(
                        "cursor-pointer transition-all hover:border-primary",
                        settings.template === template.id && "border-2 border-primary"
                      )}
                      onClick={() => setSettings({...settings, template: template.id})}
                    >
                      <CardHeader className="pb-2">
                        <CardTitle className="text-base flex items-center justify-between">
                          {template.name}
                          {settings.template === template.id && (
                            <Check className="h-4 w-4 text-primary" />
                          )}
                        </CardTitle>
                        <CardDescription className="text-xs">
                          {template.description}
                        </CardDescription>
                      </CardHeader>
                      <CardContent className="pt-0">
                        <div className="aspect-[3/4] bg-gray-100 rounded-md overflow-hidden">
                          {/* Template preview image would go here */}
                          <div className="flex items-center justify-center h-full text-gray-400">
                            <Layout className="h-8 w-8" />
                          </div>
                        </div>
                      </CardContent>
                    </Card>
                  ))}
                </div>
                
                <div className="mt-6">
                  <h3 className="text-lg font-medium mb-4">Template Options</h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-4">
                      <div className="flex items-center justify-between">
                        <Label htmlFor="coverPage" className="flex items-center gap-2">
                          <FileText className="h-4 w-4" />
                          Include Cover Page
                        </Label>
                        <Switch 
                          id="coverPage" 
                          checked={settings.coverPage}
                          onCheckedChange={(checked) => setSettings({...settings, coverPage: checked})}
                        />
                      </div>
                      <div className="flex items-center justify-between">
                        <Label htmlFor="companyLogo" className="flex items-center gap-2">
                          <ImageIcon className="h-4 w-4" />
                          Include Company Logo
                        </Label>
                        <Switch 
                          id="companyLogo" 
                          checked={settings.companyLogo}
                          onCheckedChange={(checked) => setSettings({...settings, companyLogo: checked})}
                        />
                      </div>
                      <div className="flex items-center justify-between">
                        <Label htmlFor="includeAppendix" className="flex items-center gap-2">
                          <Layers className="h-4 w-4" />
                          Include Appendix
                        </Label>
                        <Switch 
                          id="includeAppendix" 
                          checked={settings.includeAppendix}
                          onCheckedChange={(checked) => setSettings({...settings, includeAppendix: checked})}
                        />
                      </div>
                    </div>
                    <div className="space-y-4">
                      <div className="flex items-center justify-between">
                        <Label htmlFor="groupByLocation" className="flex items-center gap-2">
                          <GridIcon className="h-4 w-4" />
                          Group By Location
                        </Label>
                        <Switch 
                          id="groupByLocation" 
                          checked={settings.groupByLocation}
                          onCheckedChange={(checked) => setSettings({...settings, groupByLocation: checked})}
                        />
                      </div>
                      <div className="flex items-center justify-between">
                        <Label htmlFor="includeRecommendations" className="flex items-center gap-2">
                          <Sparkles className="h-4 w-4" />
                          Include Recommendations
                        </Label>
                        <Switch 
                          id="includeRecommendations" 
                          checked={settings.includeRecommendations}
                          onCheckedChange={(checked) => setSettings({...settings, includeRecommendations: checked})}
                        />
                      </div>
                      <div className="flex items-center justify-between">
                        <Label htmlFor="includeImages" className="flex items-center gap-2">
                          <ImageIcon className="h-4 w-4" />
                          Include Images
                        </Label>
                        <Switch 
                          id="includeImages" 
                          checked={settings.includeImages}
                          onCheckedChange={(checked) => setSettings({...settings, includeImages: checked})}
                        />
                      </div>
                    </div>
                  </div>
                </div>
              </TabsContent>

              <TabsContent value="content" className="mt-0 p-4 h-[500px]">
                <div className="space-y-6">
                  <div>
                    <Label htmlFor="executiveSummary" className="text-base font-medium">
                      Executive Summary
                    </Label>
                    <Textarea
                      id="executiveSummary"
                      placeholder="Provide an executive summary of the inspection findings..."
                      className="mt-2 min-h-[120px]"
                      value={settings.executiveSummary}
                      onChange={(e) => setSettings({...settings, executiveSummary: e.target.value})}
                    />
                    <p className="text-xs text-gray-500 mt-1">
                      This summary will appear at the beginning of the report. Focus on the key findings and their implications.
                    </p>
                  </div>

                  <div>
                    <Label htmlFor="conclusion" className="text-base font-medium">
                      Conclusion & Recommendations
                    </Label>
                    <Textarea
                      id="conclusion"
                      placeholder="Provide a conclusion and recommendations based on the inspection..."
                      className="mt-2 min-h-[120px]"
                      value={settings.conclusion}
                      onChange={(e) => setSettings({...settings, conclusion: e.target.value})}
                    />
                    <p className="text-xs text-gray-500 mt-1">
                      Summarize the overall condition and recommend next steps based on the findings.
                    </p>
                  </div>

                  <Accordion type="single" collapsible className="w-full">
                    <AccordionItem value="content-options">
                      <AccordionTrigger className="text-base font-medium">Advanced Content Options</AccordionTrigger>
                      <AccordionContent>
                        <div className="space-y-4 pt-2">
                          {/* Standard options available for all report types */}
                          <div className="flex items-center justify-between">
                            <Label htmlFor="showDates" className="flex items-center gap-2">
                              Include Due Dates
                            </Label>
                            <Switch 
                              id="showDates" 
                              checked={settings.showDates}
                              onCheckedChange={(checked) => setSettings({...settings, showDates: checked})}
                            />
                          </div>
                          
                          <div className="flex items-center justify-between">
                            <Label htmlFor="showAssignees" className="flex items-center gap-2">
                              Include Assignees
                            </Label>
                            <Switch 
                              id="showAssignees" 
                              checked={settings.showAssignees}
                              onCheckedChange={(checked) => setSettings({...settings, showAssignees: checked})}
                            />
                          </div>

                          {/* RERA Audit specific options */}
                          {settings.projectType === 'rera_audit' && (
                            <>
                              <Separator className="my-2" />
                              <h4 className="text-sm font-medium">RERA Audit Options</h4>
                              
                              <div className="flex items-center justify-between">
                                <Label htmlFor="includeNRM3Classification" className="flex items-center gap-2">
                                  Include NRM3 Classification
                                </Label>
                                <Switch 
                                  id="includeNRM3Classification" 
                                  checked={settings.includeNRM3Classification}
                                  onCheckedChange={(checked) => setSettings({...settings, includeNRM3Classification: checked})}
                                />
                              </div>
                              
                              <div className="flex items-center justify-between">
                                <Label htmlFor="includeConditionRatings" className="flex items-center gap-2">
                                  Include Condition Ratings
                                </Label>
                                <Switch 
                                  id="includeConditionRatings" 
                                  checked={settings.includeConditionRatings}
                                  onCheckedChange={(checked) => setSettings({...settings, includeConditionRatings: checked})}
                                />
                              </div>
                              
                              <div className="flex items-center justify-between">
                                <Label htmlFor="includeLifecycleCosts" className="flex items-center gap-2">
                                  Include Lifecycle Costs
                                </Label>
                                <Switch 
                                  id="includeLifecycleCosts" 
                                  checked={settings.includeLifecycleCosts}
                                  onCheckedChange={(checked) => setSettings({...settings, includeLifecycleCosts: checked})}
                                />
                              </div>
                              
                              <div className="flex items-center justify-between">
                                <Label htmlFor="includeReplacementSchedule" className="flex items-center gap-2">
                                  Include Replacement Schedule
                                </Label>
                                <Switch 
                                  id="includeReplacementSchedule" 
                                  checked={settings.includeReplacementSchedule}
                                  onCheckedChange={(checked) => setSettings({...settings, includeReplacementSchedule: checked})}
                                />
                              </div>
                            </>
                          )}
                          
                          
                          <div className="flex items-center justify-between">
                            <Label htmlFor="includeAnnotations" className="flex items-center gap-2">
                              Include Image Annotations
                            </Label>
                            <Switch 
                              id="includeAnnotations" 
                              checked={settings.includeAnnotations}
                              onCheckedChange={(checked) => setSettings({...settings, includeAnnotations: checked})}
                            />
                          </div>
                          
                          <Separator className="my-2" />
                          
                          <div>
                            <Label htmlFor="customHeader" className="text-sm">
                              Custom Header Text
                            </Label>
                            <Input
                              id="customHeader"
                              placeholder="Custom text for the report header..."
                              className="mt-1"
                              value={settings.customHeader}
                              onChange={(e) => setSettings({...settings, customHeader: e.target.value})}
                            />
                          </div>
                          
                          <div>
                            <Label htmlFor="customFooter" className="text-sm">
                              Custom Footer Text
                            </Label>
                            <Input
                              id="customFooter"
                              placeholder="Custom text for the report footer..."
                              className="mt-1"
                              value={settings.customFooter}
                              onChange={(e) => setSettings({...settings, customFooter: e.target.value})}
                            />
                          </div>
                        </div>
                      </AccordionContent>
                    </AccordionItem>
                  </Accordion>
                </div>
              </TabsContent>

              <TabsContent value="style" className="mt-0 p-4 h-[500px]">
                <div className="space-y-6">
                  <div>
                    <Label className="text-base font-medium">
                      Color Theme
                    </Label>
                    <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 mt-2">
                      {colorThemes.map((theme) => (
                        <div
                          key={theme.id}
                          className={cn(
                            "flex items-center p-3 rounded-md border cursor-pointer transition-all",
                            settings.colorTheme === theme.id
                              ? "border-2 border-primary"
                              : "border-gray-200 hover:border-gray-300"
                          )}
                          onClick={() => setSettings({...settings, colorTheme: theme.id})}
                        >
                          <div 
                            className="h-6 w-6 rounded-full mr-2"
                            style={{ backgroundColor: theme.primary }}
                          />
                          <span>{theme.name}</span>
                          {settings.colorTheme === theme.id && (
                            <Check className="h-4 w-4 ml-auto text-primary" />
                          )}
                        </div>
                      ))}
                    </div>
                  </div>

                  <div>
                    <Label className="text-base font-medium mb-2 inline-block">
                      Font Size
                    </Label>
                    <div className="flex items-center space-x-2">
                      <span className="text-sm">Smaller</span>
                      <Slider
                        defaultValue={[1]}
                        max={1.5}
                        min={0.8}
                        step={0.1}
                        value={[settings.fontSizeScale]}
                        onValueChange={(values) => setSettings({...settings, fontSizeScale: values[0]})}
                        className="flex-1"
                      />
                      <span className="text-sm">Larger</span>
                    </div>
                  </div>

                  <div className="space-y-4">
                    <Label className="text-base font-medium">
                      Layout Options
                    </Label>
                    
                    <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                      <div className="flex flex-col items-center space-y-2">
                        <Button
                          type="button"
                          variant={settings.groupByLocation ? "default" : "outline"}
                          className="w-full h-20"
                          onClick={() => setSettings({...settings, groupByLocation: true, groupBySeverity: false, groupByCategory: false})}
                        >
                          <PanelLeft className="h-6 w-6" />
                        </Button>
                        <span className="text-sm">Group by Location</span>
                      </div>
                      
                      <div className="flex flex-col items-center space-y-2">
                        <Button
                          type="button"
                          variant={settings.groupBySeverity ? "default" : "outline"}
                          className="w-full h-20"
                          onClick={() => setSettings({...settings, groupByLocation: false, groupBySeverity: true, groupByCategory: false})}
                        >
                          <PanelTop className="h-6 w-6" />
                        </Button>
                        <span className="text-sm">Group by Severity</span>
                      </div>
                      
                      <div className="flex flex-col items-center space-y-2">
                        <Button
                          type="button"
                          variant={settings.groupByCategory ? "default" : "outline"}
                          className="w-full h-20"
                          onClick={() => setSettings({...settings, groupByLocation: false, groupBySeverity: false, groupByCategory: true})}
                        >
                          <PanelRight className="h-6 w-6" />
                        </Button>
                        <span className="text-sm">Group by Category</span>
                      </div>
                    </div>
                  </div>
                </div>
              </TabsContent>

              <TabsContent value="preview" className="mt-0 p-4 h-[500px]">
                <div className="flex flex-col h-full">
                  <div className="flex items-center justify-between mb-4">
                    <h3 className="text-lg font-medium">Live Report Preview</h3>
                    <Button
                      type="button"
                      onClick={handleRefreshPreview}
                      disabled={previewLoading}
                      size="sm"
                      variant="outline"
                    >
                      {previewLoading ? (
                        <>
                          <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                          Refreshing...
                        </>
                      ) : (
                        <>
                          <RefreshCw className="h-4 w-4 mr-2" />
                          Refresh Preview
                        </>
                      )}
                    </Button>
                  </div>
                  
                  <div className="flex-1 border border-gray-200 rounded-lg overflow-hidden w-full bg-white">
                    {previewLoading ? (
                      <div className="flex items-center justify-center h-full">
                        <div className="text-center">
                          <Loader2 className="h-12 w-12 mx-auto animate-spin text-gray-400 mb-4" />
                          <p className="text-gray-500">Generating preview...</p>
                        </div>
                      </div>
                    ) : (
                      <iframe 
                        ref={previewIframeRef}
                        className="w-full h-full"
                        title="Report Preview"
                        sandbox="allow-same-origin allow-scripts allow-forms allow-popups allow-modals"
                        src="about:blank"
                      ></iframe>
                    )}
                  </div>
                  
                  <div className="text-xs text-gray-500 mt-2">
                    <h3 className="font-medium mb-2">Report Settings Summary</h3>
                    <div className="text-sm text-gray-600 space-y-1">
                      <p><span className="font-medium">Template:</span> {reportTemplates.find(t => t.id === settings.template)?.name}</p>
                      <p><span className="font-medium">Color Theme:</span> {colorThemes.find(t => t.id === settings.colorTheme)?.name}</p>
                      <p><span className="font-medium">Layout:</span> {
                        settings.groupByLocation ? "Group by Location" : 
                        settings.groupBySeverity ? "Group by Severity" : 
                        settings.groupByCategory ? "Group by Category" : "Standard"
                      }</p>
                      <div className="flex flex-wrap gap-1 justify-center mt-2">
                        {settings.coverPage && <Badge variant="outline">Cover Page</Badge>}
                        {settings.includeImages && <Badge variant="outline">Images</Badge>}
                        {settings.includeAppendix && <Badge variant="outline">Appendix</Badge>}
                        {settings.includeRecommendations && <Badge variant="outline">Recommendations</Badge>}
                      </div>
                    </div>
                  </div>
                </div>
              </TabsContent>
            </ScrollArea>
          </Tabs>
        </div>

        <DialogFooter className="pt-4 flex justify-between sm:justify-end space-x-2">
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Cancel
          </Button>
          <Button
            onClick={handleSubmit}
            disabled={generateReportMutation.isPending}
          >
            {generateReportMutation.isPending ? (
              <>
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <Download className="h-4 w-4 mr-2" />
                Generate Report
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}