import React, { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Helmet } from 'react-helmet';
import { useLocation } from 'wouter';
import InspectionLayout from '@/components/layouts/InspectionLayout';
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
} from "@/components/ui/tabs";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { 
  AlertCircle, 
  Info, 
  FileText, 
  CheckCircle, 
  Save, 
  Settings, 
  Code, 
  LayoutTemplate,
  Check,
  Image,
  Palette,
  Type
} from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { ScrollArea } from "@/components/ui/scroll-area";
import { useToast } from "@/hooks/use-toast";
import { Separator } from "@/components/ui/separator";
import { Switch } from "@/components/ui/switch";
import { apiRequest } from '@/lib/queryClient';

// Define color themes
const colorThemes = [
  { id: "blue", name: "Blue (Default)", primary: "#2563eb", secondary: "#93c5fd" },
  { id: "green", name: "Green", primary: "#16a34a", secondary: "#86efac" },
  { id: "purple", name: "Purple", primary: "#9333ea", secondary: "#d8b4fe" },
  { id: "red", name: "Red", primary: "#dc2626", secondary: "#fecaca" },
  { id: "amber", name: "Amber", primary: "#d97706", secondary: "#fde68a" },
  { id: "teal", name: "Teal", primary: "#0d9488", secondary: "#99f6e4" },
];

// Define font families
const fontFamilies = [
  { id: "default", name: "Default (System)" },
  { id: "arial", name: "Arial" },
  { id: "georgia", name: "Georgia" },
  { id: "times", name: "Times New Roman" },
  { id: "verdana", name: "Verdana" },
];

// Define page sizes
const pageSizes = [
  { id: "A4", name: "A4" },
  { id: "Letter", name: "Letter" },
  { id: "Legal", name: "Legal" },
];

// Define page orientations
const orientations = [
  { id: "portrait", name: "Portrait" },
  { id: "landscape", name: "Landscape" },
];

// Define report settings interface
interface ReportSettings {
  id?: number;
  name: string;
  isDefault: boolean;
  branding: {
    companyName: string;
    primaryColor: string;
    secondaryColor: string;
    logo: string | null;
    showLogo: boolean;
    headerText: string;
    footerText: string;
  };
  layout: {
    pageSize: 'A4' | 'Letter' | 'Legal';
    orientation: 'portrait' | 'landscape';
    marginTop: number;
    marginRight: number;
    marginBottom: number;
    marginLeft: number;
    useCustomMargins: boolean;
  };
  content: {
    fontFamily: string;
    fontSize: number;
    groupByLocation: boolean;
    showImages: boolean;
    maxImagesPerDefect: number;
    showSeverityIndicators: boolean;
    includeRecommendations: boolean;
    includeCoverPage: boolean;
    includeTableOfContents: boolean;
    includeExecutiveSummary: boolean;
    executiveSummaryTemplate: string;
    showDefectNumbers: boolean;
    showDefectDates: boolean;
    showDefectAssignees: boolean;
  };
}

// Default report settings
const defaultSettings: ReportSettings = {
  name: "Default Settings",
  isDefault: true,
  branding: {
    companyName: "Snagging By UrbanGrid",
    primaryColor: "#2563eb",
    secondaryColor: "#93c5fd",
    logo: null,
    showLogo: true,
    headerText: "",
    footerText: "Report generated by Snagging.me by UrbanGrid",
  },
  layout: {
    pageSize: 'A4',
    orientation: 'portrait',
    marginTop: 25,
    marginRight: 25,
    marginBottom: 25,
    marginLeft: 25,
    useCustomMargins: false,
  },
  content: {
    fontFamily: "default",
    fontSize: 12,
    groupByLocation: true,
    showImages: true,
    maxImagesPerDefect: 3,
    showSeverityIndicators: true,
    includeRecommendations: true,
    includeCoverPage: true,
    includeTableOfContents: true,
    includeExecutiveSummary: true,
    executiveSummaryTemplate: "This report provides a comprehensive overview of the inspection conducted at {{projectAddress}} on {{inspectionDate}}. A total of {{defectCount}} issues were identified, with {{highSeverityCount}} high priority items requiring immediate attention.",
    showDefectNumbers: true,
    showDefectDates: true,
    showDefectAssignees: false,
  }
};

export default function ReportSettings() {
  const [location, setLocation] = useLocation();
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [projectType, setProjectType] = useState<string>("snagging");
  const [activeTab, setActiveTab] = useState("branding");
  
  // Fetch report settings for specific project type
  const { data: reportSettings, isLoading: isLoadingSettings } = useQuery<ReportSettings>({
    queryKey: ['/api/reports/settings', projectType],
    queryFn: async () => {
      try {
        const response = await fetch(`/api/reports/settings?type=${projectType}`);
        if (!response.ok) {
          throw new Error('Failed to fetch settings');
        }
        return response.json();
      } catch (error) {
        console.error('Error fetching settings:', error);
        // Return project-specific default settings for the selected type
        return {
          ...defaultSettings,
          content: {
            ...defaultSettings.content,
            executiveSummaryTemplate: projectType === "snagging" 
              ? "This report provides a comprehensive overview of the inspection conducted at {{projectAddress}} on {{inspectionDate}}. A total of {{defectCount}} issues were identified, with {{highSeverityCount}} high priority items requiring immediate attention."
              : projectType === "condition_survey"
              ? "This condition survey report presents the findings of our assessment of {{projectAddress}} conducted on {{inspectionDate}}. The building is approximately {{buildingAge}} years old and is currently in {{overallCondition}} condition overall. Our assessment covered {{majorSystemsCount}} major building systems."
              : "This reserve fund study analyzes the long-term capital replacement needs for {{projectAddress}} over a {{studyPeriod}}-year period. The total estimated replacement cost is {{totalReplacementCost}} with a recommended annual contribution of {{annualContribution}}."
          }
        };
      }
    }
  });
  
  // Use settings from query or appropriate default if not available
  const [settings, setSettings] = useState<ReportSettings>(defaultSettings);
  
  // Update settings when project type changes
  React.useEffect(() => {
    if (reportSettings) {
      setSettings(reportSettings);
    } else {
      // Set default settings specific to the project type
      setSettings({
        ...defaultSettings,
        content: {
          ...defaultSettings.content,
          executiveSummaryTemplate: projectType === "snagging" 
            ? "This report provides a comprehensive overview of the inspection conducted at {{projectAddress}} on {{inspectionDate}}. A total of {{defectCount}} issues were identified, with {{highSeverityCount}} high priority items requiring immediate attention."
            : projectType === "condition_survey"
            ? "This condition survey report presents the findings of our assessment of {{projectAddress}} conducted on {{inspectionDate}}. The building is approximately {{buildingAge}} years old and is currently in {{overallCondition}} condition overall. Our assessment covered {{majorSystemsCount}} major building systems."
            : "This reserve fund study analyzes the long-term capital replacement needs for {{projectAddress}} over a {{studyPeriod}}-year period. The total estimated replacement cost is {{totalReplacementCost}} with a recommended annual contribution of {{annualContribution}}."
        }
      });
    }
  }, [projectType, reportSettings]);
  
  
  // Save settings mutation
  const saveSettingsMutation = useMutation({
    mutationFn: (settings: ReportSettings) => {
      return apiRequest(`/api/reports/settings?type=${projectType}`, {
        method: 'PUT',
        body: settings,
      });
    },
    onSuccess: () => {
      toast({
        title: "Settings Saved",
        description: `Your ${projectType.replace('_', ' ')} report template has been updated successfully.`,
      });
      queryClient.invalidateQueries({ queryKey: ['/api/reports/settings', projectType] });
    },
    onError: (error) => {
      toast({
        title: "Error Saving Template",
        description: "There was a problem saving your report template. Please try again.",
        variant: "destructive",
      });
    }
  });
  
  // Handle save settings
  const handleSaveSettings = () => {
    saveSettingsMutation.mutate(settings);
  };
  
  // Handle setting changes
  const updateSetting = (path: string[], value: any) => {
    setSettings(prev => {
      const newSettings = { ...prev };
      let current: any = newSettings;
      
      // Navigate to the nested property
      for (let i = 0; i < path.length - 1; i++) {
        current = current[path[i] as keyof typeof current];
      }
      
      // Set the value
      const lastKey = path[path.length - 1];
      current[lastKey] = value;
      return newSettings;
    });
  };
  
  if (isLoadingSettings) {
    return (
      <InspectionLayout>
        <div className="flex items-center justify-center min-h-[50vh]">
          <div className="w-10 h-10 border-4 border-primary border-t-transparent rounded-full animate-spin"></div>
        </div>
      </InspectionLayout>
    );
  }
  
  return (
    <InspectionLayout 
      title="Report Settings" 
      description="Customize your report appearance and content"
      actionButton={
        <div className="flex items-center gap-2">
          <Button 
            onClick={() => setLocation("/inspection/reports")}
            variant="outline"
            size="sm"
          >
            Cancel
          </Button>
          <Button 
            onClick={handleSaveSettings}
            disabled={saveSettingsMutation.isPending}
            variant="default"
            size="sm"
            className="bg-green-600 hover:bg-green-700"
          >
            {saveSettingsMutation.isPending ? (
              <>Saving...</>
            ) : (
              <>
                <Save className="mr-2 h-4 w-4" />
                Save Settings
              </>
            )}
          </Button>
        </div>
      }
    >
      <Helmet>
        <title>Report Settings - Inspection System</title>
      </Helmet>
      
      <div className="space-y-6">
        {/* Project Type Tabs */}
        <Card className="border-0 shadow-sm bg-white">
          <CardContent className="p-6">
            <Tabs value={projectType} onValueChange={setProjectType} className="w-full">
              <TabsList className="w-full grid grid-cols-3 mb-4">
                <TabsTrigger value="snagging">
                  Snagging Inspection
                </TabsTrigger>
                <TabsTrigger value="condition_survey">
                  Condition Survey
                </TabsTrigger>
                <TabsTrigger value="reserve_fund_study">
                  Reserve Fund Study
                </TabsTrigger>
              </TabsList>
              
              <div className="mb-6">
                {projectType === "snagging" && (
                  <Alert variant="default" className="bg-blue-50 border-blue-200">
                    <Info className="h-4 w-4 text-blue-500" />
                    <AlertTitle>Snagging Inspection Report Template</AlertTitle>
                    <AlertDescription>
                      Customize the appearance and content for property snagging inspection reports. 
                      These settings will be applied to all property handover and defect inspection reports.
                    </AlertDescription>
                  </Alert>
                )}
                
                {projectType === "condition_survey" && (
                  <Alert variant="default" className="bg-amber-50 border-amber-200">
                    <Info className="h-4 w-4 text-amber-500" />
                    <AlertTitle>Condition Survey Report Template</AlertTitle>
                    <AlertDescription>
                      Customize the appearance and content for RERA condition survey reports.
                      These settings will be applied to all building condition assessment reports.
                    </AlertDescription>
                  </Alert>
                )}
                
                {projectType === "reserve_fund_study" && (
                  <Alert variant="default" className="bg-green-50 border-green-200">
                    <Info className="h-4 w-4 text-green-500" />
                    <AlertTitle>Reserve Fund Study Report Template</AlertTitle>
                    <AlertDescription>
                      Customize the appearance and content for RERA reserve fund study reports.
                      These settings will be applied to all lifecycle cost planning and reserve fund reports.
                    </AlertDescription>
                  </Alert>
                )}
              </div>
            </Tabs>
          </CardContent>
        </Card>
        
        {/* Main content */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          <div className="lg:col-span-8">
            <Card className="border-0 shadow-sm bg-white">
              <CardHeader className="pb-2">
                <CardTitle>Report Appearance and Content</CardTitle>
                <CardDescription>
                  Customize how your inspection reports look and what they include
                </CardDescription>
              </CardHeader>
              <CardContent>
                <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
                  <TabsList className="grid grid-cols-3 mb-6">
                    <TabsTrigger value="branding">
                      <Palette className="mr-2 h-4 w-4" />
                      Branding
                    </TabsTrigger>
                    <TabsTrigger value="layout">
                      <FileText className="mr-2 h-4 w-4" />
                      Layout
                    </TabsTrigger>
                    <TabsTrigger value="content">
                      <Type className="mr-2 h-4 w-4" />
                      Content
                    </TabsTrigger>
                  </TabsList>
                  
                  {/* Branding Settings */}
                  <TabsContent value="branding" className="mt-0">
                    <div className="space-y-6">
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                          <Label htmlFor="companyName">Company Name</Label>
                          <Input 
                            id="companyName" 
                            value={settings.branding.companyName}
                            onChange={(e) => updateSetting(['branding', 'companyName'], e.target.value)}
                            placeholder="Your Company Name"
                          />
                        </div>
                        
                        <div>
                          <Label htmlFor="primaryColor">Primary Color</Label>
                          <div className="flex gap-2">
                            <Input 
                              type="color" 
                              id="primaryColor" 
                              value={settings.branding.primaryColor} 
                              onChange={(e) => updateSetting(['branding', 'primaryColor'], e.target.value)}
                              className="w-16 p-1 h-10"
                            />
                            <Select 
                              value={colorThemes.find(t => t.primary === settings.branding.primaryColor)?.id || "custom"}
                              onValueChange={(value) => {
                                const theme = colorThemes.find(t => t.id === value);
                                if (theme) {
                                  updateSetting(['branding', 'primaryColor'], theme.primary);
                                  updateSetting(['branding', 'secondaryColor'], theme.secondary);
                                }
                              }}
                            >
                              <SelectTrigger className="flex-1">
                                <SelectValue placeholder="Select color theme" />
                              </SelectTrigger>
                              <SelectContent>
                                {colorThemes.map(theme => (
                                  <SelectItem key={theme.id} value={theme.id}>
                                    <div className="flex items-center">
                                      <div 
                                        className="w-4 h-4 rounded-full mr-2" 
                                        style={{ backgroundColor: theme.primary }}
                                      ></div>
                                      {theme.name}
                                    </div>
                                  </SelectItem>
                                ))}
                              </SelectContent>
                            </Select>
                          </div>
                        </div>
                      </div>
                      
                      <Separator />
                      
                      <div className="space-y-4">
                        <div className="flex items-center justify-between">
                          <div>
                            <Label htmlFor="showLogo">Show Company Logo</Label>
                            <p className="text-sm text-muted-foreground">
                              Display your company logo on report headers and cover page
                            </p>
                          </div>
                          <Switch 
                            id="showLogo" 
                            checked={settings.branding.showLogo}
                            onCheckedChange={(checked) => updateSetting(['branding', 'showLogo'], checked)}
                          />
                        </div>
                        
                        {settings.branding.showLogo && (
                          <div>
                            <Label htmlFor="logoUpload">Company Logo</Label>
                            <div className="mt-2 flex items-center gap-4">
                              {settings.branding.logo ? (
                                <div className="w-40 h-20 relative border rounded overflow-hidden">
                                  <img 
                                    src={settings.branding.logo} 
                                    alt="Company Logo" 
                                    className="object-contain w-full h-full" 
                                  />
                                  <Button
                                    variant="destructive"
                                    size="sm"
                                    className="absolute top-1 right-1"
                                    onClick={() => updateSetting(['branding', 'logo'], null)}
                                  >
                                    Remove
                                  </Button>
                                </div>
                              ) : (
                                <div className="w-40 h-20 border rounded flex items-center justify-center bg-muted">
                                  <Image className="w-8 h-8 text-muted-foreground" />
                                </div>
                              )}
                              
                              <div className="flex-1">
                                <Input 
                                  id="logoUpload" 
                                  type="file" 
                                  accept="image/*"
                                  onChange={(e) => {
                                    const file = e.target.files?.[0];
                                    if (file) {
                                      // Normally we'd upload this file to the server
                                      // For now we'll use a URL technique to simulate this
                                      const reader = new FileReader();
                                      reader.onload = (event) => {
                                        updateSetting(['branding', 'logo'], event.target?.result);
                                      };
                                      reader.readAsDataURL(file);
                                    }
                                  }}
                                />
                                <p className="text-sm text-muted-foreground mt-1">
                                  Recommended: PNG or JPG, 300x100 pixels
                                </p>
                              </div>
                            </div>
                          </div>
                        )}
                      </div>
                      
                      <Separator />
                      
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                          <Label htmlFor="headerText">Custom Header Text</Label>
                          <Input 
                            id="headerText" 
                            value={settings.branding.headerText}
                            onChange={(e) => updateSetting(['branding', 'headerText'], e.target.value)}
                            placeholder="Optional header text for all pages"
                          />
                        </div>
                        
                        <div>
                          <Label htmlFor="footerText">Custom Footer Text</Label>
                          <Input 
                            id="footerText" 
                            value={settings.branding.footerText}
                            onChange={(e) => updateSetting(['branding', 'footerText'], e.target.value)}
                            placeholder="Optional footer text for all pages"
                          />
                        </div>
                      </div>
                    </div>
                  </TabsContent>
                  
                  {/* Layout Settings */}
                  <TabsContent value="layout" className="mt-0">
                    <div className="space-y-6">
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                          <Label htmlFor="pageSize">Page Size</Label>
                          <Select 
                            value={settings.layout.pageSize}
                            onValueChange={(value) => updateSetting(['layout', 'pageSize'], value)}
                          >
                            <SelectTrigger id="pageSize">
                              <SelectValue placeholder="Select page size" />
                            </SelectTrigger>
                            <SelectContent>
                              {pageSizes.map(size => (
                                <SelectItem key={size.id} value={size.id}>
                                  {size.name}
                                </SelectItem>
                              ))}
                            </SelectContent>
                          </Select>
                        </div>
                        
                        <div>
                          <Label htmlFor="orientation">Orientation</Label>
                          <Select 
                            value={settings.layout.orientation}
                            onValueChange={(value) => updateSetting(['layout', 'orientation'], value)}
                          >
                            <SelectTrigger id="orientation">
                              <SelectValue placeholder="Select page orientation" />
                            </SelectTrigger>
                            <SelectContent>
                              {orientations.map(orientation => (
                                <SelectItem key={orientation.id} value={orientation.id}>
                                  {orientation.name}
                                </SelectItem>
                              ))}
                            </SelectContent>
                          </Select>
                        </div>
                      </div>
                      
                      <Separator />
                      
                      <div>
                        <div className="flex items-center justify-between mb-4">
                          <div>
                            <Label htmlFor="useCustomMargins">Custom Margins</Label>
                            <p className="text-sm text-muted-foreground">
                              Set custom page margins for your reports
                            </p>
                          </div>
                          <Switch 
                            id="useCustomMargins" 
                            checked={settings.layout.useCustomMargins}
                            onCheckedChange={(checked) => updateSetting(['layout', 'useCustomMargins'], checked)}
                          />
                        </div>
                        
                        {settings.layout.useCustomMargins && (
                          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                            <div>
                              <Label htmlFor="marginTop">Top (mm)</Label>
                              <Input 
                                id="marginTop" 
                                type="number"
                                min="0"
                                max="100"
                                value={settings.layout.marginTop}
                                onChange={(e) => updateSetting(['layout', 'marginTop'], Number(e.target.value))}
                              />
                            </div>
                            
                            <div>
                              <Label htmlFor="marginRight">Right (mm)</Label>
                              <Input 
                                id="marginRight" 
                                type="number"
                                min="0"
                                max="100"
                                value={settings.layout.marginRight}
                                onChange={(e) => updateSetting(['layout', 'marginRight'], Number(e.target.value))}
                              />
                            </div>
                            
                            <div>
                              <Label htmlFor="marginBottom">Bottom (mm)</Label>
                              <Input 
                                id="marginBottom" 
                                type="number"
                                min="0"
                                max="100"
                                value={settings.layout.marginBottom}
                                onChange={(e) => updateSetting(['layout', 'marginBottom'], Number(e.target.value))}
                              />
                            </div>
                            
                            <div>
                              <Label htmlFor="marginLeft">Left (mm)</Label>
                              <Input 
                                id="marginLeft" 
                                type="number"
                                min="0"
                                max="100"
                                value={settings.layout.marginLeft}
                                onChange={(e) => updateSetting(['layout', 'marginLeft'], Number(e.target.value))}
                              />
                            </div>
                          </div>
                        )}
                      </div>
                    </div>
                  </TabsContent>
                  
                  {/* Content Settings */}
                  <TabsContent value="content" className="mt-0">
                    <div className="space-y-6">
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                          <Label htmlFor="fontFamily">Font Family</Label>
                          <Select 
                            value={settings.content.fontFamily}
                            onValueChange={(value) => updateSetting(['content', 'fontFamily'], value)}
                          >
                            <SelectTrigger id="fontFamily">
                              <SelectValue placeholder="Select font family" />
                            </SelectTrigger>
                            <SelectContent>
                              {fontFamilies.map(font => (
                                <SelectItem key={font.id} value={font.id}>
                                  {font.name}
                                </SelectItem>
                              ))}
                            </SelectContent>
                          </Select>
                        </div>
                        
                        <div>
                          <Label htmlFor="fontSize">Font Size</Label>
                          <div className="flex items-center gap-2">
                            <Input 
                              id="fontSize" 
                              type="number"
                              min="8"
                              max="16"
                              value={settings.content.fontSize}
                              onChange={(e) => updateSetting(['content', 'fontSize'], Number(e.target.value))}
                              className="w-20"
                            />
                            <span className="text-sm">pt</span>
                            <Input 
                              type="range"
                              min="8"
                              max="16"
                              value={settings.content.fontSize}
                              onChange={(e) => updateSetting(['content', 'fontSize'], Number(e.target.value))}
                              className="flex-1"
                            />
                          </div>
                        </div>
                      </div>
                      
                      <Separator />
                      
                      <div className="space-y-4">
                        <h3 className="text-lg font-medium">Report Structure</h3>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                          <div className="space-y-4">
                            <div className="flex items-center justify-between">
                              <Label htmlFor="includeCoverPage">Cover Page</Label>
                              <Switch 
                                id="includeCoverPage" 
                                checked={settings.content.includeCoverPage}
                                onCheckedChange={(checked) => updateSetting(['content', 'includeCoverPage'], checked)}
                              />
                            </div>
                            
                            <div className="flex items-center justify-between">
                              <Label htmlFor="includeTableOfContents">Table of Contents</Label>
                              <Switch 
                                id="includeTableOfContents" 
                                checked={settings.content.includeTableOfContents}
                                onCheckedChange={(checked) => updateSetting(['content', 'includeTableOfContents'], checked)}
                              />
                            </div>
                            
                            <div className="flex items-center justify-between">
                              <Label htmlFor="includeExecutiveSummary">Executive Summary</Label>
                              <Switch 
                                id="includeExecutiveSummary" 
                                checked={settings.content.includeExecutiveSummary}
                                onCheckedChange={(checked) => updateSetting(['content', 'includeExecutiveSummary'], checked)}
                              />
                            </div>
                          </div>
                          
                          <div className="space-y-4">
                            <div className="flex items-center justify-between">
                              <Label htmlFor="groupByLocation">Group by Location</Label>
                              <Switch 
                                id="groupByLocation" 
                                checked={settings.content.groupByLocation}
                                onCheckedChange={(checked) => updateSetting(['content', 'groupByLocation'], checked)}
                              />
                            </div>
                            
                            <div className="flex items-center justify-between">
                              <Label htmlFor="showSeverityIndicators">Severity Indicators</Label>
                              <Switch 
                                id="showSeverityIndicators" 
                                checked={settings.content.showSeverityIndicators}
                                onCheckedChange={(checked) => updateSetting(['content', 'showSeverityIndicators'], checked)}
                              />
                            </div>
                            
                            <div className="flex items-center justify-between">
                              <Label htmlFor="includeRecommendations">Recommendations</Label>
                              <Switch 
                                id="includeRecommendations" 
                                checked={settings.content.includeRecommendations}
                                onCheckedChange={(checked) => updateSetting(['content', 'includeRecommendations'], checked)}
                              />
                            </div>
                          </div>
                        </div>
                      </div>
                      
                      {settings.content.includeExecutiveSummary && (
                        <>
                          <Separator />
                          <div>
                            <Label htmlFor="executiveSummaryTemplate">Executive Summary Template</Label>
                            <p className="text-sm text-muted-foreground mb-2">
                              Use placeholders for dynamic content.
                            </p>
                            <div className="mb-2">
                              {projectType === "snagging" && (
                                <div className="p-2 bg-blue-50 rounded-sm text-xs">
                                  <span className="font-medium text-blue-600">Snagging placeholders:</span> {'{{projectAddress}}, {{inspectionDate}}, {{defectCount}}, {{highSeverityCount}}, {{clientName}}'}
                                </div>
                              )}
                              {projectType === "condition_survey" && (
                                <div className="p-2 bg-amber-50 rounded-sm text-xs">
                                  <span className="font-medium text-amber-600">Condition Survey placeholders:</span> {'{{projectAddress}}, {{inspectionDate}}, {{buildingAge}}, {{overallCondition}}, {{majorSystemsCount}}'}
                                </div>
                              )}
                              {projectType === "reserve_fund_study" && (
                                <div className="p-2 bg-green-50 rounded-sm text-xs">
                                  <span className="font-medium text-green-600">Reserve Fund placeholders:</span> {'{{projectAddress}}, {{inspectionDate}}, {{studyPeriod}}, {{totalReplacementCost}}, {{annualContribution}}'}
                                </div>
                              )}
                            </div>
                            <Textarea 
                              id="executiveSummaryTemplate" 
                              value={settings.content.executiveSummaryTemplate}
                              onChange={(e) => updateSetting(['content', 'executiveSummaryTemplate'], e.target.value)}
                              rows={4}
                              placeholder={projectType === "snagging" 
                                ? "This report provides a comprehensive overview of the inspection conducted at {{projectAddress}} on {{inspectionDate}}. A total of {{defectCount}} issues were identified, with {{highSeverityCount}} high priority items requiring immediate attention."
                                : projectType === "condition_survey"
                                ? "This condition survey report presents the findings of our assessment of {{projectAddress}} conducted on {{inspectionDate}}. The building is approximately {{buildingAge}} years old and is currently in {{overallCondition}} condition overall. Our assessment covered {{majorSystemsCount}} major building systems."
                                : "This reserve fund study analyzes the long-term capital replacement needs for {{projectAddress}} over a {{studyPeriod}}-year period. The total estimated replacement cost is {{totalReplacementCost}} with a recommended annual contribution of {{annualContribution}}."
                              }
                            />
                          </div>
                        </>
                      )}
                      
                      <Separator />
                      
                      <div className="space-y-4">
                        <h3 className="text-lg font-medium">Defect Content Settings</h3>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                          <div className="space-y-4">
                            <div className="flex items-center justify-between">
                              <Label htmlFor="showDefectNumbers">Show Defect Numbers</Label>
                              <Switch 
                                id="showDefectNumbers" 
                                checked={settings.content.showDefectNumbers}
                                onCheckedChange={(checked) => updateSetting(['content', 'showDefectNumbers'], checked)}
                              />
                            </div>
                            
                            <div className="flex items-center justify-between">
                              <Label htmlFor="showDefectDates">Show Defect Dates</Label>
                              <Switch 
                                id="showDefectDates" 
                                checked={settings.content.showDefectDates}
                                onCheckedChange={(checked) => updateSetting(['content', 'showDefectDates'], checked)}
                              />
                            </div>
                            
                            <div className="flex items-center justify-between">
                              <Label htmlFor="showDefectAssignees">Show Defect Assignees</Label>
                              <Switch 
                                id="showDefectAssignees" 
                                checked={settings.content.showDefectAssignees}
                                onCheckedChange={(checked) => updateSetting(['content', 'showDefectAssignees'], checked)}
                              />
                            </div>
                          </div>
                          
                          <div className="space-y-4">
                            <div className="flex items-center justify-between">
                              <Label htmlFor="showImages">Show Images</Label>
                              <Switch 
                                id="showImages" 
                                checked={settings.content.showImages}
                                onCheckedChange={(checked) => updateSetting(['content', 'showImages'], checked)}
                              />
                            </div>
                            
                            {settings.content.showImages && (
                              <div>
                                <Label htmlFor="maxImagesPerDefect">Max Images Per Defect</Label>
                                <div className="flex items-center gap-2">
                                  <Input 
                                    id="maxImagesPerDefect" 
                                    type="number"
                                    min="1"
                                    max="10"
                                    value={settings.content.maxImagesPerDefect}
                                    onChange={(e) => updateSetting(['content', 'maxImagesPerDefect'], Number(e.target.value))}
                                    className="w-20"
                                  />
                                  <Input 
                                    type="range"
                                    min="1"
                                    max="10"
                                    value={settings.content.maxImagesPerDefect}
                                    onChange={(e) => updateSetting(['content', 'maxImagesPerDefect'], Number(e.target.value))}
                                    className="flex-1"
                                  />
                                </div>
                              </div>
                            )}
                          </div>
                        </div>
                      </div>
                    </div>
                  </TabsContent>
                </Tabs>
              </CardContent>
              <CardFooter className="flex justify-end border-t p-4">
                <Button 
                  onClick={handleSaveSettings}
                  disabled={saveSettingsMutation.isPending}
                  className="bg-green-600 hover:bg-green-700"
                >
                  {saveSettingsMutation.isPending ? (
                    <>Saving...</>
                  ) : (
                    <>
                      <Save className="mr-2 h-4 w-4" />
                      Save Settings
                    </>
                  )}
                </Button>
              </CardFooter>
            </Card>
          </div>
          
          <div className="lg:col-span-4">
            <Card className="border-0 shadow-sm bg-white">
              <CardHeader className="pb-2">
                <CardTitle>Report Preview</CardTitle>
                <CardDescription>
                  See how your settings affect the report appearance
                </CardDescription>
              </CardHeader>
              <CardContent className="p-6">
                <div className="border rounded-md p-4 aspect-[3/4] bg-white relative overflow-hidden shadow-sm">
                  {/* Sample Report Preview */}
                  <div 
                    className="w-full h-full"
                    style={{
                      fontFamily: settings.content.fontFamily === 'default' ? 'system-ui, sans-serif' : settings.content.fontFamily,
                      fontSize: `${settings.content.fontSize}px`,
                    }}
                  >
                    {/* Header */}
                    <div className="border-b pb-2 mb-4 flex justify-between items-center text-sm">
                      {settings.branding.showLogo && settings.branding.logo && (
                        <img 
                          src={settings.branding.logo} 
                          alt="Logo" 
                          className="h-8 object-contain" 
                        />
                      )}
                      {!settings.branding.logo && settings.branding.companyName && (
                        <div 
                          style={{ color: settings.branding.primaryColor }}
                          className="font-bold"
                        >
                          {settings.branding.companyName}
                        </div>
                      )}
                      <div className="text-xs">{settings.branding.headerText}</div>
                    </div>
                    
                    {/* Sample Content */}
                    <div className="text-center mb-4">
                      <h1 
                        className="text-xl font-bold"
                        style={{ color: settings.branding.primaryColor }}
                      >
                        Property Inspection Report
                      </h1>
                      <p className="text-sm text-gray-500">123 Sample Street, Dubai</p>
                    </div>
                    
                    {settings.content.groupByLocation && (
                      <div 
                        className="mb-3 rounded px-2 py-1 text-sm font-medium"
                        style={{ 
                          backgroundColor: settings.branding.primaryColor + '20',
                          color: settings.branding.primaryColor
                        }}
                      >
                        Living Room
                      </div>
                    )}
                    
                    {/* Sample Defect */}
                    <div className="mb-4 border rounded p-2">
                      {settings.content.showDefectNumbers && (
                        <div className="text-xs text-gray-500 mb-1">
                          Defect #1
                        </div>
                      )}
                      
                      <div className="flex gap-2 items-start">
                        {settings.content.showSeverityIndicators && (
                          <div 
                            className="w-4 h-4 rounded-full mt-1"
                            style={{ backgroundColor: "red" }}
                          ></div>
                        )}
                        <div>
                          <div className="font-medium">Wall Crack</div>
                          <p className="text-sm">
                            A vertical crack on the wall approximately 50cm in length.
                          </p>
                          {settings.content.showDefectDates && (
                            <div className="text-xs text-gray-500 mt-1">
                              Identified: 12 Apr 2023
                            </div>
                          )}
                        </div>
                      </div>
                      
                      {settings.content.showImages && (
                        <div className="mt-2 flex gap-1">
                          <div className="w-16 h-12 bg-gray-100 rounded border"></div>
                          <div className="w-16 h-12 bg-gray-100 rounded border"></div>
                        </div>
                      )}
                      
                      {settings.content.includeRecommendations && (
                        <div className="mt-2 text-sm">
                          <span className="font-medium">Recommendation:</span> Fill crack with appropriate filler and repaint.
                        </div>
                      )}
                    </div>
                    
                    {/* Footer */}
                    <div className="absolute bottom-0 left-0 right-0 border-t pt-2 text-xs text-center text-gray-500">
                      {settings.branding.footerText}
                    </div>
                  </div>
                  
                  {/* Paper size overlay */}
                  <div className="absolute inset-0 border-2 border-dashed border-gray-200 pointer-events-none"></div>
                </div>
                
                <div className="mt-4 text-sm text-muted-foreground">
                  <div className="font-medium mb-1">Current Settings</div>
                  <ul className="space-y-1">
                    <li>• Theme: {colorThemes.find(t => t.primary === settings.branding.primaryColor)?.name || "Custom"}</li>
                    <li>• Page: {settings.layout.pageSize}, {settings.layout.orientation}</li>
                    <li>• Font: {fontFamilies.find(f => f.id === settings.content.fontFamily)?.name}, {settings.content.fontSize}pt</li>
                    <li>• Group by: {settings.content.groupByLocation ? "Location" : "None"}</li>
                  </ul>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </InspectionLayout>
  );
}